name: Trigger Central Documentation Repository Workflow

on:
  push:
    branches:
      - master
      - mkdocs
      - main

jobs:
  dispatch:
    name: triger central
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['aryan-bhokare/ParentRepo']
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.DOCS_ACCESS_TOKEN }}" \
            --request POST \
            --data '{"event_type": "update-docs", "client_payload": { "foo": "bar" }}' https://api.github.com/repos/${{ matrix.repo }}/dispatches